In [ ]:
import duckdb
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [74]:
con = duckdb.connect(r"C:\Users\jrf24\Incendios-Forestales-\data\BaseDeDatos_Working.db")

In [ ]:
con.execute("SHOW TABLES").df()

           name
0         causa
1  climatologia
2         danos
3    demografia
4   diccionario
5        estado
6     incendios
7    municipios
8   operaciones
9    vegetacion

In [76]:
# cargar tablas
df_incendios = con.execute("SELECT * FROM incendios").df()
df_clima = con.execute("SELECT * FROM climatologia").df()
df_causa = con.execute("SELECT * FROM causa").df()
df_veg = con.execute("SELECT * FROM vegetacion").df()
df_demo = con.execute("SELECT * FROM demografia").df()
df_danos = con.execute("SELECT * FROM danos").df()

In [77]:
df_clima.columns

Index(['id_registro', 'id_variable', 'id_clave_inc', 'fecha_de_observacion',
       'resultado_numerico'],
      dtype='str')

In [78]:
df_clima["fecha_de_observacion"] = pd.to_datetime(df_clima["fecha_de_observacion"])
df_incendios["fecha_inicio"] = pd.to_datetime(df_incendios["fecha_inicio"])

In [79]:
df_clima = df_clima.merge(
    df_incendios[["id_clave_inc", "fecha_inicio"]],
    on="id_clave_inc",
    how="left"
)

In [80]:
df_clima["dias_antes"] = (
    df_clima["fecha_inicio"] - df_clima["fecha_de_observacion"]
).dt.days

In [81]:
df_clima = df_clima[df_clima["dias_antes"] >= 0]

In [82]:
def crear_pivot(df, nombre, condicion):
    temp = df[condicion]
    
    pivot = temp.pivot_table(
        index="id_clave_inc",
        columns="id_variable",
        values="resultado_numerico",
        aggfunc="mean"
    )
    
    pivot.columns = [f"{col}_{nombre}" for col in pivot.columns]
    
    return pivot.reset_index()

In [83]:
pivot_0d = crear_pivot(df_clima, "0d", df_clima["dias_antes"] == 0)

pivot_3d = crear_pivot(df_clima, "3d", (df_clima["dias_antes"] > 0) & (df_clima["dias_antes"] <= 3))

pivot_7d = crear_pivot(df_clima, "7d", (df_clima["dias_antes"] > 0) & (df_clima["dias_antes"] <= 7))

pivot_15d = crear_pivot(df_clima, "15d", (df_clima["dias_antes"] > 0) & (df_clima["dias_antes"] <= 15))

In [84]:
df_clima_final = pivot_0d

df_clima_final = df_clima_final.merge(pivot_3d, on="id_clave_inc", how="left")
df_clima_final = df_clima_final.merge(pivot_7d, on="id_clave_inc", how="left")
df_clima_final = df_clima_final.merge(pivot_15d, on="id_clave_inc", how="left")

In [85]:
df = df_incendios.merge(df_clima, on="id_clave_inc", how="left")

In [86]:
df = df_incendios.merge(df_clima_final, on="id_clave_inc", how="left")

In [87]:
df = df.merge(df_veg, on="id_vegetacion", how="left")

In [88]:
df = df.merge(df_causa, on="id_causa", how="left")

In [89]:
df = df.merge(df_demo, on="id_cvegeo", how="left")

In [90]:
df = df.merge(df_danos, on="id_clave_inc", how="left")

In [91]:
df.head()

,id_clave_inc,id_cvegeo,id_causa,id_vegetacion,latitud,longitud,fecha_inicio,tipo_de_incendio,anio_x,AIRMASS_0d,...,r_70_74,r_75_79,r_80_84,r_85_mm,hojarasca,arbustivo,herbaceo,arbolado_adulto,renuevo,tamanio
0,15-15-0156,15039,32,28,19.309111,-99.788834,2015-03-02,superficial,2015,3.3,...,2573,1744,1130,915,0.0,0.0,15.0,0.0,0.0,11 a 20 hectareas
1,15-15-0156,15039,32,28,19.309111,-99.788834,2015-03-02,superficial,2015,3.3,...,3092,1847,1073,839,0.0,0.0,15.0,0.0,0.0,11 a 20 hectareas
2,15-15-0156,15039,32,28,19.309111,-99.788834,2015-03-02,superficial,2015,3.3,...,2620,1289,738,478,0.0,0.0,15.0,0.0,0.0,11 a 20 hectareas
3,15-15-0156,15039,32,28,19.309111,-99.788834,2015-03-02,superficial,2015,3.3,...,3092,1743,978,723,0.0,0.0,15.0,0.0,0.0,11 a 20 hectareas
4,15-15-0156,15039,32,28,19.309111,-99.788834,2015-03-02,superficial,2015,3.3,...,2869,1501,848,590,0.0,0.0,15.0,0.0,0.0,11 a 20 hectareas

In [92]:
df["temp_combustible"] = df["TSOIL6_0d"] + df["T2M_0d"]

df["estres_hidrico"] = df["NDVI_7d"] - df["NDMI_7d"]

In [93]:
df["presion_humana"] = df["pob_total"] / (
    df["latitud"].abs() + df["longitud"].abs() + 1
)

In [94]:
df["fecha_inicio"] = pd.to_datetime(df["fecha_inicio"])

df["mes"] = df["fecha_inicio"].dt.month
df["estacion"] = df["mes"] % 12 // 3 + 1

In [95]:
[col for col in df.columns if "NDVI" in col or "NDMI" in col or "TSOIL" in col]

['TSOIL1_0d',
 'TSOIL2_0d',
 'TSOIL3_0d',
 'TSOIL4_0d',
 'TSOIL5_0d',
 'TSOIL6_0d',
 'NDMI_3d',
 'NDVI_3d',
 'TSOIL1_3d',
 'TSOIL2_3d',
 'TSOIL3_3d',
 'TSOIL4_3d',
 'TSOIL5_3d',
 'TSOIL6_3d',
 'NDMI_7d',
 'NDVI_7d',
 'TSOIL1_7d',
 'TSOIL2_7d',
 'TSOIL3_7d',
 'TSOIL4_7d',
 'TSOIL5_7d',
 'TSOIL6_7d',
 'NDMI_15d',
 'NDVI_15d',
 'TSOIL1_15d',
 'TSOIL2_15d',
 'TSOIL3_15d',
 'TSOIL4_15d',
 'TSOIL5_15d',
 'TSOIL6_15d']

In [96]:
df["TSOIL_0d_mean"] = df[[f"TSOIL{i}_0d" for i in range(1,7)]].mean(axis=1)
df["TSOIL_3d_mean"] = df[[f"TSOIL{i}_3d" for i in range(1,7)]].mean(axis=1)
df["TSOIL_7d_mean"] = df[[f"TSOIL{i}_7d" for i in range(1,7)]].mean(axis=1)
df["TSOIL_15d_mean"] = df[[f"TSOIL{i}_15d" for i in range(1,7)]].mean(axis=1)

In [97]:
df["NDVI_mean"] = df[["NDVI_3d","NDVI_7d","NDVI_15d"]].mean(axis=1)

df["NDMI_mean"] = df[["NDMI_3d","NDMI_7d","NDMI_15d"]].mean(axis=1)

In [98]:
df["NDVI_trend"] = df["NDVI_3d"] - df["NDVI_15d"]

In [99]:
df["NDMI_trend"] = df["NDMI_3d"] - df["NDMI_15d"]

In [100]:
df["TSOIL_mean"] = df[
    ["TSOIL1_3d","TSOIL2_3d","TSOIL3_3d","TSOIL4_3d","TSOIL5_3d","TSOIL6_3d"]
].mean(axis=1)

In [101]:
df["TSOIL_trend"] = df["TSOIL6_3d"] - df["TSOIL6_15d"]

In [102]:
df["riesgo"] = pd.qcut(
    df["NDVI_trend"] - df["NDMI_trend"] + df["TSOIL_trend"],
    3,
    labels=["bajo", "medio", "alto"]
)

In [105]:
df.columns

Index(['id_clave_inc', 'id_cvegeo', 'id_causa', 'id_vegetacion', 'latitud',
       'longitud', 'fecha_inicio', 'tipo_de_incendio', 'anio_x', 'AIRMASS_0d',
       ...
       'TSOIL_3d_mean', 'TSOIL_7d_mean', 'TSOIL_15d_mean', 'NDVI_mean',
       'NDMI_mean', 'NDVI_trend', 'NDMI_trend', 'TSOIL_mean', 'TSOIL_trend',
       'riesgo'],
      dtype='str', length=541)

In [106]:
df_model = df.copy()

In [108]:
features = [
    # clima
    "TSOIL6", "NDVI", "NDMI", "EVPTRNS", "T2M",

    # vegetación
    "id_vegetacion", "estres_hidrico", "temp_combustible",

    # demografía
    "poblacion_total", "presion_humana",

    # espacial / temporal
    "latitud", "longitud", "anio", "mes", "estacion"
]

In [111]:
print(df_model.columns.tolist())

['id_clave_inc', 'id_cvegeo', 'id_causa', 'id_vegetacion', 'latitud', 'longitud', 'fecha_inicio', 'tipo_de_incendio', 'anio_x', 'AIRMASS_0d', 'ALLSKY_KT_0d', 'ALLSKY_NKT_0d', 'ALLSKY_SFC_LW_DWN_0d', 'ALLSKY_SFC_LW_UP_0d', 'ALLSKY_SFC_PAR_DIFF_0d', 'ALLSKY_SFC_PAR_DIRH_0d', 'ALLSKY_SFC_PAR_TOT_0d', 'ALLSKY_SFC_SW_DIFF_0d', 'ALLSKY_SFC_SW_DIRH_0d', 'ALLSKY_SFC_SW_DNI_0d', 'ALLSKY_SFC_SW_DWN_0d', 'ALLSKY_SFC_SW_UP_0d', 'ALLSKY_SFC_UVA_0d', 'ALLSKY_SFC_UVB_0d', 'ALLSKY_SFC_UV_INDEX_0d', 'ALLSKY_SRF_ALB_0d', 'AOD_55_0d', 'AOD_55_ADJ_0d', 'AOD_84_0d', 'CDD0_0d', 'CDD18_3_0d', 'CLOUD_AMT_0d', 'CLOUD_AMT_DAY_0d', 'CLOUD_AMT_NIGHT_0d', 'CLOUD_OD_0d', 'CLRSKY_DAYS_0d', 'CLRSKY_KT_0d', 'CLRSKY_NKT_0d', 'CLRSKY_SFC_LW_DWN_0d', 'CLRSKY_SFC_LW_UP_0d', 'CLRSKY_SFC_PAR_DIFF_0d', 'CLRSKY_SFC_PAR_DIRH_0d', 'CLRSKY_SFC_PAR_TOT_0d', 'CLRSKY_SFC_SW_DIFF_0d', 'CLRSKY_SFC_SW_DIRH_0d', 'CLRSKY_SFC_SW_DNI_0d', 'CLRSKY_SFC_SW_DWN_0d', 'CLRSKY_SFC_SW_UP_0d', 'CLRSKY_SRF_ALB_0d', 'DISPH_0d', 'EVLAND_0d', 'EVPTRNS_0d', 'FROST_DAYS_0d', 'FRSEAICE_0d', 'FRSNO_0d', 'GWETPROF_0d', 'GWETROOT_0d', 'GWETTOP_0d', 'HDD0_0d', 'HDD18_3_0d', 'MIDDAY_INSOL_0d', 'ORIGINAL_ALLSKY_SFC_SW_DIFF_0d', 'ORIGINAL_ALLSKY_SFC_SW_DIRH_0d', 'PBLTOP_0d', 'PRECSNO_0d', 'PRECSNOLAND_0d', 'PRECTOTCORR_0d', 'PS_0d', 'PSH_0d', 'PW_0d', 'QV10M_0d', 'QV2M_0d', 'RH2M_0d', 'RHOA_0d', 'SLP_0d', 'SNODP_0d', 'SRF_ALB_ADJ_0d', 'T10M_0d', 'T10M_MAX_0d', 'T10M_MIN_0d', 'T10M_RANGE_0d', 'T2M_0d', 'T2MDEW_0d', 'T2MWET_0d', 'T2M_MAX_0d', 'T2M_MIN_0d', 'T2M_RANGE_0d', 'TO3_0d', 'TOA_SW_DNI_0d', 'TOA_SW_DWN_0d', 'TQV_0d', 'TROPPB_0d', 'TROPQ_0d', 'TROPT_0d', 'TS_0d', 'TSOIL1_0d', 'TSOIL2_0d', 'TSOIL3_0d', 'TSOIL4_0d', 'TSOIL5_0d', 'TSOIL6_0d', 'TSURF_0d', 'TS_ADJ_0d', 'TS_MAX_0d', 'TS_MIN_0d', 'TS_RANGE_0d', 'U10M_0d', 'U2M_0d', 'U50M_0d', 'V10M_0d', 'V2M_0d', 'V50M_0d', 'WD10M_0d', 'WD2M_0d', 'WD50M_0d', 'WS10M_0d', 'WS10M_MAX_0d', 'WS10M_MIN_0d', 'WS10M_RANGE_0d', 'WS2M_0d', 'WS2M_MAX_0d', 'WS2M_MIN_0d', 'WS2M_RANGE_0d', 'WS50M_0d', 'WS50M_MAX_0d', 'WS50M_MIN_0d', 'WS50M_RANGE_0d', 'Z0M_0d', 'AIRMASS_3d', 'ALLSKY_KT_3d', 'ALLSKY_NKT_3d', 'ALLSKY_SFC_LW_DWN_3d', 'ALLSKY_SFC_LW_UP_3d', 'ALLSKY_SFC_PAR_DIFF_3d', 'ALLSKY_SFC_PAR_DIRH_3d', 'ALLSKY_SFC_PAR_TOT_3d', 'ALLSKY_SFC_SW_DIFF_3d', 'ALLSKY_SFC_SW_DIRH_3d', 'ALLSKY_SFC_SW_DNI_3d', 'ALLSKY_SFC_SW_DWN_3d', 'ALLSKY_SFC_SW_UP_3d', 'ALLSKY_SFC_UVA_3d', 'ALLSKY_SFC_UVB_3d', 'ALLSKY_SFC_UV_INDEX_3d', 'ALLSKY_SRF_ALB_3d', 'AOD_55_3d', 'AOD_55_ADJ_3d', 'AOD_84_3d', 'CDD0_3d', 'CDD18_3_3d', 'CLOUD_AMT_3d', 'CLOUD_AMT_DAY_3d', 'CLOUD_AMT_NIGHT_3d', 'CLOUD_OD_3d', 'CLRSKY_DAYS_3d', 'CLRSKY_KT_3d', 'CLRSKY_NKT_3d', 'CLRSKY_SFC_LW_DWN_3d', 'CLRSKY_SFC_LW_UP_3d', 'CLRSKY_SFC_PAR_DIFF_3d', 'CLRSKY_SFC_PAR_DIRH_3d', 'CLRSKY_SFC_PAR_TOT_3d', 'CLRSKY_SFC_SW_DIFF_3d', 'CLRSKY_SFC_SW_DIRH_3d', 'CLRSKY_SFC_SW_DNI_3d', 'CLRSKY_SFC_SW_DWN_3d', 'CLRSKY_SFC_SW_UP_3d', 'CLRSKY_SRF_ALB_3d', 'DISPH_3d', 'EVLAND_3d', 'EVPTRNS_3d', 'FROST_DAYS_3d', 'FRSEAICE_3d', 'FRSNO_3d', 'GWETPROF_3d', 'GWETROOT_3d', 'GWETTOP_3d', 'HDD0_3d', 'HDD18_3_3d', 'MIDDAY_INSOL_3d', 'NDMI_3d', 'NDVI_3d', 'NDWI_3d', 'ORIGINAL_ALLSKY_SFC_SW_DIFF_3d', 'ORIGINAL_ALLSKY_SFC_SW_DIRH_3d', 'PBLTOP_3d', 'PRECSNO_3d', 'PRECSNOLAND_3d', 'PRECTOTCORR_3d', 'PS_3d', 'PSH_3d', 'PW_3d', 'QV10M_3d', 'QV2M_3d', 'RH2M_3d', 'RHOA_3d', 'SLP_3d', 'SNODP_3d', 'SRF_ALB_ADJ_3d', 'T10M_3d', 'T10M_MAX_3d', 'T10M_MIN_3d', 'T10M_RANGE_3d', 'T2M_3d', 'T2MDEW_3d', 'T2MWET_3d', 'T2M_MAX_3d', 'T2M_MIN_3d', 'T2M_RANGE_3d', 'TO3_3d', 'TOA_SW_DNI_3d', 'TOA_SW_DWN_3d', 'TQV_3d', 'TROPPB_3d', 'TROPQ_3d', 'TROPT_3d', 'TS_3d', 'TSOIL1_3d', 'TSOIL2_3d', 'TSOIL3_3d', 'TSOIL4_3d', 'TSOIL5_3d', 'TSOIL6_3d', 'TSURF_3d', 'TS_ADJ_3d', 'TS_MAX_3d', 'TS_MIN_3d', 'TS_RANGE_3d', 'U10M_3d', 'U2M_3d', 'U50M_3d', 'V10M_3d', 'V2M_3d', 'V50M_3d', 'WD10M_3d', 'WD2M_3d', 'WD50M_3d', 'WS10M_3d', 'WS10M_MAX_3d', 'WS10M_MIN_3d', 'WS10M_RANGE_3d', 'WS2M_3d', 'WS2M_MAX_3d', 'WS2M_MIN_3d', 'WS2M_RANGE_3d', 'WS50M_3d', 'WS50M_MAX_3d', 'WS50M_MIN_3d', 'WS50M_RANGE_3d', 'Z0M_3d', 'AIRMASS_7d', 'ALLSKY_KT_7d', 'ALLSKY_NKT_7d', 'ALLSKY_SFC_LW_DWN_7d', 'ALLSKY_SFC_LW_UP_7d', 'ALLSKY_SFC_PAR_DIFF_7d', 'ALLSKY_SFC_PAR_DIRH_7d', 'ALLSKY_SFC_PAR_TOT_7d', 'ALLSKY_SFC_SW_DIFF_7d', 'ALLSKY_SFC_SW_DIRH_7d', 'ALLSKY_SFC_SW_DNI_7d', 'ALLSKY_SFC_SW_DWN_7d', 'ALLSKY_SFC_SW_UP_7d', 'ALLSKY_SFC_UVA_7d', 'ALLSKY_SFC_UVB_7d', 'ALLSKY_SFC_UV_INDEX_7d', 'ALLSKY_SRF_ALB_7d', 'AOD_55_7d', 'AOD_55_ADJ_7d', 'AOD_84_7d', 'CDD0_7d', 'CDD18_3_7d', 'CLOUD_AMT_7d', 'CLOUD_AMT_DAY_7d', 'CLOUD_AMT_NIGHT_7d', 'CLOUD_OD_7d', 'CLRSKY_DAYS_7d', 'CLRSKY_KT_7d', 'CLRSKY_NKT_7d', 'CLRSKY_SFC_LW_DWN_7d', 'CLRSKY_SFC_LW_UP_7d', 'CLRSKY_SFC_PAR_DIFF_7d', 'CLRSKY_SFC_PAR_DIRH_7d', 'CLRSKY_SFC_PAR_TOT_7d', 'CLRSKY_SFC_SW_DIFF_7d', 'CLRSKY_SFC_SW_DIRH_7d', 'CLRSKY_SFC_SW_DNI_7d', 'CLRSKY_SFC_SW_DWN_7d', 'CLRSKY_SFC_SW_UP_7d', 'CLRSKY_SRF_ALB_7d', 'DISPH_7d', 'EVLAND_7d', 'EVPTRNS_7d', 'FROST_DAYS_7d', 'FRSEAICE_7d', 'FRSNO_7d', 'GWETPROF_7d', 'GWETROOT_7d', 'GWETTOP_7d', 'HDD0_7d', 'HDD18_3_7d', 'MIDDAY_INSOL_7d', 'NDMI_7d', 'NDVI_7d', 'NDWI_7d', 'ORIGINAL_ALLSKY_SFC_SW_DIFF_7d', 'ORIGINAL_ALLSKY_SFC_SW_DIRH_7d', 'PBLTOP_7d', 'PRECSNO_7d', 'PRECSNOLAND_7d', 'PRECTOTCORR_7d', 'PS_7d', 'PSH_7d', 'PW_7d', 'QV10M_7d', 'QV2M_7d', 'RH2M_7d', 'RHOA_7d', 'SLP_7d', 'SNODP_7d', 'SRF_ALB_ADJ_7d', 'T10M_7d', 'T10M_MAX_7d', 'T10M_MIN_7d', 'T10M_RANGE_7d', 'T2M_7d', 'T2MDEW_7d', 'T2MWET_7d', 'T2M_MAX_7d', 'T2M_MIN_7d', 'T2M_RANGE_7d', 'TO3_7d', 'TOA_SW_DNI_7d', 'TOA_SW_DWN_7d', 'TQV_7d', 'TROPPB_7d', 'TROPQ_7d', 'TROPT_7d', 'TS_7d', 'TSOIL1_7d', 'TSOIL2_7d', 'TSOIL3_7d', 'TSOIL4_7d', 'TSOIL5_7d', 'TSOIL6_7d', 'TSURF_7d', 'TS_ADJ_7d', 'TS_MAX_7d', 'TS_MIN_7d', 'TS_RANGE_7d', 'U10M_7d', 'U2M_7d', 'U50M_7d', 'V10M_7d', 'V2M_7d', 'V50M_7d', 'WD10M_7d', 'WD2M_7d', 'WD50M_7d', 'WS10M_7d', 'WS10M_MAX_7d', 'WS10M_MIN_7d', 'WS10M_RANGE_7d', 'WS2M_7d', 'WS2M_MAX_7d', 'WS2M_MIN_7d', 'WS2M_RANGE_7d', 'WS50M_7d', 'WS50M_MAX_7d', 'WS50M_MIN_7d', 'WS50M_RANGE_7d', 'Z0M_7d', 'AIRMASS_15d', 'ALLSKY_KT_15d', 'ALLSKY_NKT_15d', 'ALLSKY_SFC_LW_DWN_15d', 'ALLSKY_SFC_LW_UP_15d', 'ALLSKY_SFC_PAR_DIFF_15d', 'ALLSKY_SFC_PAR_DIRH_15d', 'ALLSKY_SFC_PAR_TOT_15d', 'ALLSKY_SFC_SW_DIFF_15d', 'ALLSKY_SFC_SW_DIRH_15d', 'ALLSKY_SFC_SW_DNI_15d', 'ALLSKY_SFC_SW_DWN_15d', 'ALLSKY_SFC_SW_UP_15d', 'ALLSKY_SFC_UVA_15d', 'ALLSKY_SFC_UVB_15d', 'ALLSKY_SFC_UV_INDEX_15d', 'ALLSKY_SRF_ALB_15d', 'AOD_55_15d', 'AOD_55_ADJ_15d', 'AOD_84_15d', 'CDD0_15d', 'CDD18_3_15d', 'CLOUD_AMT_15d', 'CLOUD_AMT_DAY_15d', 'CLOUD_AMT_NIGHT_15d', 'CLOUD_OD_15d', 'CLRSKY_DAYS_15d', 'CLRSKY_KT_15d', 'CLRSKY_NKT_15d', 'CLRSKY_SFC_LW_DWN_15d', 'CLRSKY_SFC_LW_UP_15d', 'CLRSKY_SFC_PAR_DIFF_15d', 'CLRSKY_SFC_PAR_DIRH_15d', 'CLRSKY_SFC_PAR_TOT_15d', 'CLRSKY_SFC_SW_DIFF_15d', 'CLRSKY_SFC_SW_DIRH_15d', 'CLRSKY_SFC_SW_DNI_15d', 'CLRSKY_SFC_SW_DWN_15d', 'CLRSKY_SFC_SW_UP_15d', 'CLRSKY_SRF_ALB_15d', 'DISPH_15d', 'EVLAND_15d', 'EVPTRNS_15d', 'FROST_DAYS_15d', 'FRSEAICE_15d', 'FRSNO_15d', 'GWETPROF_15d', 'GWETROOT_15d', 'GWETTOP_15d', 'HDD0_15d', 'HDD18_3_15d', 'MIDDAY_INSOL_15d', 'NDMI_15d', 'NDVI_15d', 'NDWI_15d', 'ORIGINAL_ALLSKY_SFC_SW_DIFF_15d', 'ORIGINAL_ALLSKY_SFC_SW_DIRH_15d', 'PBLTOP_15d', 'PRECSNO_15d', 'PRECSNOLAND_15d', 'PRECTOTCORR_15d', 'PS_15d', 'PSH_15d', 'PW_15d', 'QV10M_15d', 'QV2M_15d', 'RH2M_15d', 'RHOA_15d', 'SLP_15d', 'SNODP_15d', 'SRF_ALB_ADJ_15d', 'T10M_15d', 'T10M_MAX_15d', 'T10M_MIN_15d', 'T10M_RANGE_15d', 'T2M_15d', 'T2MDEW_15d', 'T2MWET_15d', 'T2M_MAX_15d', 'T2M_MIN_15d', 'T2M_RANGE_15d', 'TO3_15d', 'TOA_SW_DNI_15d', 'TOA_SW_DWN_15d', 'TQV_15d', 'TROPPB_15d', 'TROPQ_15d', 'TROPT_15d', 'TS_15d', 'TSOIL1_15d', 'TSOIL2_15d', 'TSOIL3_15d', 'TSOIL4_15d', 'TSOIL5_15d', 'TSOIL6_15d', 'TSURF_15d', 'TS_ADJ_15d', 'TS_MAX_15d', 'TS_MIN_15d', 'TS_RANGE_15d', 'U10M_15d', 'U2M_15d', 'U50M_15d', 'V10M_15d', 'V2M_15d', 'V50M_15d', 'WD10M_15d', 'WD2M_15d', 'WD50M_15d', 'WS10M_15d', 'WS10M_MAX_15d', 'WS10M_MIN_15d', 'WS10M_RANGE_15d', 'WS2M_15d', 'WS2M_MAX_15d', 'WS2M_MIN_15d', 'WS2M_RANGE_15d', 'WS50M_15d', 'WS50M_MAX_15d', 'WS50M_MIN_15d', 'WS50M_RANGE_15d', 'Z0M_15d', 'regimen_del_fuego', 'tipo_de_vegetacion', 'causa', 'causa_especifica', 'anio_y', 'sexo', 'pob_total', 'r_00_04', 'r_05_09', 'r_10_14', 'r_15_19', 'r_20_24', 'r_25_29', 'r_30_34', 'r_35_39', 'r_40_44', 'r_45_49', 'r_50_54', 'r_55_59', 'r_60_64', 'r_65_69', 'r_70_74', 'r_75_79', 'r_80_84', 'r_85_mm', 'hojarasca', 'arbustivo', 'herbaceo', 'arbolado_adulto', 'renuevo', 'tamanio', 'temp_combustible', 'estres_hidrico', 'presion_humana', 'mes', 'estacion', 'TSOIL_0d_mean', 'TSOIL_3d_mean', 'TSOIL_7d_mean', 'TSOIL_15d_mean', 'NDVI_mean', 'NDMI_mean', 'NDVI_trend', 'NDMI_trend', 'TSOIL_mean', 'TSOIL_trend', 'riesgo']

In [112]:
df = df.copy()

In [113]:
features = [
    # Vegetación
    "NDVI_mean",
    "NDMI_mean",
    "NDVI_trend",
    "NDMI_trend",

    # Suelo/clima resumido
    "TSOIL_mean",
    "TSOIL_trend",

    # Demografía
    "pob_total",
    "presion_humana",

    # incendios/estructura
    "mes",
    "estacion",
    "id_vegetacion",
    "id_causa"
]

df_model = df[features + ["riesgo"]].dropna()

In [114]:
X = df_model[features]
y = df_model["riesgo"]

In [115]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=150,
    max_depth=12,
    n_jobs=-1,
    random_state=42
)

model.fit(X, y)

RandomForestClassifier(max_depth=12, n_estimators=150, n_jobs=-1,
                       random_state=42)

In [116]:
import pandas as pd

importancias = pd.Series(
    model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

importancias

TSOIL_trend       0.839780
TSOIL_mean        0.070092
mes               0.049408
estacion          0.012463
pob_total         0.006017
NDMI_mean         0.005623
NDVI_mean         0.005246
presion_humana    0.005137
id_causa          0.003239
id_vegetacion     0.002995
NDMI_trend        0.000000
NDVI_trend        0.000000
dtype: float64

In [119]:
importancias.head(20)

TSOIL_trend       0.839780
TSOIL_mean        0.070092
mes               0.049408
estacion          0.012463
pob_total         0.006017
NDMI_mean         0.005623
NDVI_mean         0.005246
presion_humana    0.005137
id_causa          0.003239
id_vegetacion     0.002995
NDMI_trend        0.000000
NDVI_trend        0.000000
dtype: float64

In [120]:
RandomForestClassifier(
    max_depth=20,
    min_samples_leaf=5,
    class_weight="balanced"
)

RandomForestClassifier(class_weight='balanced', max_depth=20,
                       min_samples_leaf=5)

In [122]:
import pandas as pd

importancias = pd.Series(
    model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

importancias

TSOIL_trend       0.839780
TSOIL_mean        0.070092
mes               0.049408
estacion          0.012463
pob_total         0.006017
NDMI_mean         0.005623
NDVI_mean         0.005246
presion_humana    0.005137
id_causa          0.003239
id_vegetacion     0.002995
NDMI_trend        0.000000
NDVI_trend        0.000000
dtype: float64

In [121]:
df_model = df_model.drop(columns=["TSOIL_trend"])

In [123]:
import pandas as pd

importancias = pd.Series(
    model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

importancias

TSOIL_trend       0.839780
TSOIL_mean        0.070092
mes               0.049408
estacion          0.012463
pob_total         0.006017
NDMI_mean         0.005623
NDVI_mean         0.005246
presion_humana    0.005137
id_causa          0.003239
id_vegetacion     0.002995
NDMI_trend        0.000000
NDVI_trend        0.000000
dtype: float64

In [124]:
clima_vars = [c for c in df.columns if any(x in c for x in [
    "TSOIL", "T2M", "T10M", "EVPTRNS", "NDMI", "NDVI",
    "PREC", "RH2M", "WS10M", "SLP", "AIRMASS"
])]

In [125]:
vegetacion_vars = [
    "id_vegetacion",
    "NDVI_mean", "NDMI_mean",
    "NDVI_trend", "NDMI_trend",
    "TSOIL_mean", "TSOIL_trend",
    "hojarasca", "arbustivo", "herbaceo",
    "arbolado_adulto", "renuevo"
]

In [126]:
humano_vars = [
    "pob_total",
    "presion_humana",
    "id_causa",
    "mes",
    "estacion"
]

In [127]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

model.fit(X, y)

RandomForestClassifier(n_estimators=200, n_jobs=-1, random_state=42)

In [128]:
import pandas as pd

importancias = pd.Series(
    model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

In [129]:
def importance_group(group_vars, importancias):
    return importancias.loc[
        [v for v in group_vars if v in importancias.index]
    ].sum()

In [130]:
score_clima = importance_group(clima_vars, importancias)
score_veg = importance_group(vegetacion_vars, importancias)
score_humano = importance_group(humano_vars, importancias)

In [131]:
pd.Series({
    "Clima": score_clima,
    "Vegetación": score_veg,
    "Humano": score_humano
}).sort_values(ascending=False)

Vegetación    0.922743
Clima         0.919055
Humano        0.077257
dtype: float64